name: "Unit Tests"

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20", "^1.20"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Tests
        run: go test -v -timeout 300s -cover github.com/studio-b12/elk
